import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import { type ReactNode } from "react";
import { cookieToInitialState } from "@alchemy/aa-alchemy/config";
import AppHeader from "@/components/_app/AppHeader";
import { config } from "@/alchemy";

import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: ReactNode }) {
  const initialState = cookieToInitialState(
    config,
    headers().get("cookie") || undefined
  );
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers initialState={initialState}>
          <AppHeader />
          <div>{props.children}</div>
        </Providers>
      </body>
    </html>
  );
}
