import { Connector } from "wagmi";

function getIcon(connector: Connector): string | undefined {
  if (connector.icon) {
    return connector.icon;
  }
  if (connector.id === "coinbaseWalletSDK") {
    return "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNzAiIGhlaWdodD0iNzAiIHZpZXdCb3g9IjAgMCA3MCA3MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMzUiIGN5PSIzNSIgcj0iMzUiIGZpbGw9IiMwMDUyRkYiLz4KPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0xMSAzNUMxMSA0OC4yNTMzIDIxLjc0NjcgNTkgMzUgNTlDNDguMjUzMyA1OSA1OSA0OC4yNTMzIDU5IDM1QzU5IDIxLjc0NjcgNDguMjUzMyAxMSAzNSAxMUMyMS43NDY3IDExIDExIDIxLjc0NjcgMTEgMzVaTTI4Ljg2NjcgMjcuMjY2N0MyNy45OCAyNy4yNjY3IDI3LjI2NjcgMjcuOTggMjcuMjY2NyAyOC44NjY3VjQxLjEzMzNDMjcuMjY2NyA0Mi4wMiAyNy45OCA0Mi43MzMzIDI4Ljg2NjcgNDIuNzMzM0g0MS4xMzMzQzQyLjAyIDQyLjczMzMgNDIuNzMzMyA0Mi4wMiA0Mi43MzMzIDQxLjEzMzNWMjguODY2N0M0Mi43MzMzIDI3Ljk4IDQyLjAyIDI3LjI2NjcgNDEuMTMzMyAyNy4yNjY3SDI4Ljg2NjdaIiBmaWxsPSJ3aGl0ZSIvPgo8L3N2Zz4K";
  }
  return undefined;
}

// eslint-disable-next-line import/prefer-default-export
export { getIcon };
